version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: problem5_db
    restart: always
    environment:
      POSTGRES_USER: user_problem5
      POSTGRES_PASSWORD: password_problem5
      POSTGRES_DB: problem5_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_backend
    restart: always
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: problem5_db
      DB_USER: user_problem5
      DB_PASSWORD: password_problem5
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
